apiVersion: ENC[AES256_GCM,data:JP0=,iv:pfQ5pQcn5a4hlBV39PuJpe8WQlQvFH9VvoetAAX/G9o=,tag:pO8/IMMl+BcFWW/u4BvxsA==,type:str]
kind: ENC[AES256_GCM,data:CUp4iKkp,iv:gBdKQbMrrWOr3OT7OeDMa95YM4W71V03sotVf/6tqxU=,tag:Cq8TC8y0OLCTPf9Ew/KWZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RYqlKhrAM42v3saC4HpOBYy5l/+tuwFd1QW1+pSKRicWejtUzm6OvFAoOQ==,iv:WsL+baQ/EskOVlf0o9ReyfOx+C8qdDZwmqebJJohBoU=,tag:ncmdp6+0L8LPMb1XwJYRPw==,type:str]
    namespace: ENC[AES256_GCM,data:MgFWSSEd0JspF73ODNORs1trPEUBu8bkYX8pPZbued7E0Rdl,iv:Ut3zALMqrxDArrCgqoh15ZCRCnrGMQFr7LyohCz14Qc=,tag:M/TVn9c1UPnYwz0hYHLbXQ==,type:str]
stringData:
    api_token: ENC[AES256_GCM,data:2HmRtP5/NTxPoXpGlzLKfolIAtYMGhO7ElyA1pXCLsuEMfPtPilxLA==,iv:dIu+eAKWu/boBRIwEexU3+0Hyb7fr4029Jf5p65uYqk=,tag:WEx0+hB3DftBGM6stSVUqQ==,type:str]
    account_id: ENC[AES256_GCM,data:S53TKQPcqsGwotiG7V1C1p8mYt8ZiJofoTTG33j8plg=,iv:4v9MauC0Rz8m4NelrRP78oL2kcmduv83JcPUFvl0+5U=,tag:TFgzKEdDPRS4cUKx89hVKg==,type:str]
    tunnel_name: ENC[AES256_GCM,data:dEqC,iv:xLJvt+sbOzsc0WOceQKZLLZt3dnvPFAre+JZ4dZy8sU=,tag:W1ScBZahvG15gnRFSXCLRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-18T15:30:07Z"
    mac: ENC[AES256_GCM,data:dNPPyU/CGlXWCGc8mP5mTYWhOEuf990Sduu9+xB83wCj9YFZOi31HKiesqTyKUl0nbvotGKxSx6Wh+V4kNLp0opg5uYtRUTGWx3UwbyYzmABHOaXDgx9R/b26c+DeKXReUtR3brMhFbhKFDw96Qmz/fT+vJUBaL3wrcJYj2HqGg=,iv:JokdvpZcoFBSG/1JEroZzSsiByb9taVSxee8tyWf39c=,tag:aGmoFrX6QBB7BUlVWkwlbQ==,type:str]
    pgp:
        - created_at: "2024-09-18T15:30:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAwcX++/Ro9ISAQwAkVplZgInwH1lpj9dEbEaK72W/MR2IWmS+XIA2MQSKx2W
            o9IGWPnt4OJyzljglU5yYHSi4DD+gvYoMVoSglLl0cbnYIzSRdZV8xihWzEgG8zU
            Mh1ZY2PQ1AUsU8LKD3DS7MLsYKrsAoRoe6xt7F85C1YpzJQQ2AMGM//4Tp9D3ORY
            r6hCOocJenp6jBcJL1PKecT1E1IwuO31Fa3WJlfCLIXw+HcWok60ylsrzrhAJQPH
            gO8j3xY8x/2wW+8vVuo4WbJrZ0Ez9XIGY1x/ROURvgVMsmhpFTfd2g6ezWQ3+4nb
            x67VUeTHRHu6DZyb/eiJkIEqIpNpXaTS0Sojs7nCITL16Q5RzJry52RjLuQhDOgp
            pR9f4AmwvxEH4+DodlRzKqSCO9BGZ7MfrCxeYUVrMEmZu78bQlXGkMHyQd6J2F7T
            nOQw993XypTmXIRDdfAiKgofAP0AfLVmmDst70gKHuqXdjmYgECvTkvGNhD/wegW
            LUzRIXjhOt4CLXfUBbcN1GgBCQIQSASyOS6lDkwS1xAIkRyjntmnDWXkiqnYLnLr
            ngpazKiCum4nyDEI0PDuJxhOimu/ItgtqUsGgdsYBnk0crLv+u5Z620bpS6UvZnA
            Y09jTopva5xo5GJPw9qcJ0TlKhzCl6J2zA==
            =o2yk
            -----END PGP MESSAGE-----
          fp: 1C9CD7A21901FC06DCEC0DEB74D9DB37B03A4804
    unencrypted_suffix: _unencrypted
    version: 3.9.0
