deployments:
  - path: apps/kluctl
  - path: apps/cloudflare-tunnel-ingress-controller
  - path: apps/whoami
  - path: apps/grafana
  - path: apps/prometheus
  - path: apps/loki
  - git:
      url: https://github.com/kluctl/kluctl.git
      subDir: install/controller
      ref:
        tag: v2.25.1

vars:
  - file: secrets.yaml
