apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-ingress-controller-secret
  namespace: cloudflare-tunnel-ingress-controller
stringData:
  api_token: "{{ secrets.cf_tunnels.api_token }}"
  account_id: "{{ secrets.cf_tunnels.account_id }}"
  tunnel_name: "{{ secrets.cf_tunnels.tunnel_name }}"
