datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      # - name: Loki
      #   type: loki
      #   url: http://loki-gateway.loki.svc.cluster.local
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.prometheus.svc.cluster.local

persistence:
  type: pvc
  enabled: true

grafana.ini:
  server:
    root_url: https://grafana.whoison.top
