apiVersion: v2
appVersion: 9.0.2
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.27.0
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.5.38
- condition: postgresql-ha.enabled
  name: postgresql-ha
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 14.3.7
- condition: redis-cluster.enabled
  name: redis-cluster
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 11.0.7
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 20.2.1
description: Forgejo Helm chart for Kubernetes
home: https://forgejo.org/
icon: https://code.forgejo.org/forgejo/forgejo/raw/branch/forgejo/assets/logo.svg
keywords:
- git
- issue tracker
- code review
- wiki
- forgejo
- gitea
- gogs
maintainers:
- email: michael.kriese@visualon.de
  name: Michael Kriese
name: forgejo
sources:
- https://code.forgejo.org/forgejo-helm/forgejo-helm
- https://codeberg.org/forgejo/forgejo
type: application
version: 10.1.1
